name = "highest-bid-worker"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "highest-bid-db"
database_id = "37d0a766-af9b-43ec-b321-33d09e0bee0d"
